# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Uses the bisection method to find the root of a univariate function, denoted g.
#'
#' @param gp <func> First derivative of g.
#' @param a <double> Initial guess for the left endpoint.
#' @param b <double> Initial guess for the right endpoint.
#' @param eps <double> Tolerance used to classify convergence.
#' @param maxIter <int> Maximum number of iterations to perform before stopping.
#' @return <list> Root of g and the number of iterations required for convergence.
unibisection <- function(gp, a, b, eps, maxIter) {
    .Call(`_optimization_unibisection`, gp, a, b, eps, maxIter)
}

#' Uses the Fisher scoring method to find the root of a univariate likelihood function, denoted l.
#'
#' @param lp <func> First derivative of l, function of only the parameter.
#' @param fisherInfo <func> Fisher information, function of only the parameter.
#' @param n <int> Sample size.
#' @param a <double> Initial guess for parameter.
#' @param eps <double> Tolerance used to classify convergence.
#' @param maxIter <int> Maximum number of iterations to perform before stopping.
#' @return <list> Estimate for parameter and the number of iterations required for convergence.
unifisher <- function(lp, fisherInfo, n, a, eps, maxIter) {
    .Call(`_optimization_unifisher`, lp, fisherInfo, n, a, eps, maxIter)
}

#' Uses the Newton method to find the root of a univariate function, denoted g.
#'
#' @param gp <func> First derivative of g.
#' @param gpp <func> Second derivative of g.
#' @param a <double> Initial guess for the root.
#' @param eps <double> Tolerance used to classify convergence.
#' @param maxIter <int> Maximum number of iterations to perform before stopping.
#' @return <list> Root of g and the number of iterations required for convergence.
uninewton <- function(gp, gpp, a, eps, maxIter) {
    .Call(`_optimization_uninewton`, gp, gpp, a, eps, maxIter)
}

#' Uses the secant method to find the root of a univariate function, denoted g.
#'
#' @param gp <func> First derivative of g.
#' @param a <double> Initial guess for the left endpoint.
#' @param b <double> Initial guess for the right endpoint.
#' @param eps <double> Tolerance used to classify convergence.
#' @param maxIter <int> Maximum number of iterations to perform before stopping.
#' @return <list> Root of g and the number of iterations required for convergence.
unisecant <- function(gp, a, b, eps, maxIter) {
    .Call(`_optimization_unisecant`, gp, a, b, eps, maxIter)
}

